cd exSev
PORT=5000 node app.js &
cd ../orgSev
ORGSEVCONFIG_PORT=5010 ORGSEVCONFIG_ORGID=F ORGSEVCONFIG_ORGNAME=Friday node app.js &
ORGSEVCONFIG_PORT=5020 ORGSEVCONFIG_ORGID=H ORGSEVCONFIG_ORGNAME=HappyGO node app.js &
cd ../shopSev
SHOPSEVCONFIG_PORT=5011 SHOPSEVCONFIG_ORGID=F SHOPSEVCONFIG_SHOPNAME="SHOP FA" SHOPSEVCONFIG_SHOPID="F-001" SHOPSEVCONFIG_ORGPORT=5010 node app.js &
SHOPSEVCONFIG_PORT=5012 SHOPSEVCONFIG_ORGID=F SHOPSEVCONFIG_SHOPNAME="SHOP FB" SHOPSEVCONFIG_SHOPID="F-002" SHOPSEVCONFIG_ORGPORT=5010 node app.js &
SHOPSEVCONFIG_PORT=5021 SHOPSEVCONFIG_ORGID=H SHOPSEVCONFIG_SHOPNAME="SHOP HA" SHOPSEVCONFIG_SHOPID="H-001" SHOPSEVCONFIG_ORGPORT=5020 node app.js &
SHOPSEVCONFIG_PORT=5022 SHOPSEVCONFIG_ORGID=H SHOPSEVCONFIG_SHOPNAME="SHOP HB" SHOPSEVCONFIG_SHOPID="H-002" SHOPSEVCONFIG_ORGPORT=5020 node app.js &




