export CHAINCODE_NAME=loyalty
export channelName=mychannel
export F_ADDRESS=http://localhost:5010
export H_ADDRESS=http://localhost:5020 
export EX_ADDRESS=http://localhost:5003 
export F_GATEWAY=http://localhost:4001
export H_GATEWAY=http://localhost:4001
export EX_GATEWAY=http://localhost:4001

cd ../exSev
PORT=5003 ISSUERADDRESS_F=$F_ADDRESS ISSUERADDRESS_H=$H_ADDRESS  GATEWAYADDRESS=http://localhost:4001 FABRIC_CCNAME=$CHAINCODE_NAME node app.js&
cd ../orgSev
ORGSEVCONFIG_PORT=5010 EX_ADDRESS=$EX_ADDRESS GATEWAYADDRESS=http://localhost:4001 ISSUERADDRESS_F=$F_ADDRESS ISSUERADDRESS_H=$H_ADDRESS ORGSEVCONFIG_ORGID=F ORGSEVCONFIG_ORGNAME=Friday FABRIC_CCNAME=$CHAINCODE_NAME node app.js &
ORGSEVCONFIG_PORT=5020 EX_ADDRESS=$EX_ADDRESS GATEWAYADDRESS=http://localhost:4001 ISSUERADDRESS_F=$F_ADDRESS ISSUERADDRESS_H=$H_ADDRESS ORGSEVCONFIG_ORGID=H ORGSEVCONFIG_ORGNAME=HappyGO FABRIC_CCNAME=$CHAINCODE_NAME node app.js &
cd ../shopSev
SHOPSEVCONFIG_PORT=5011 SHOPSEVCONFIG_ORGID=F SHOPSEVCONFIG_SHOPNAME="SHOP FA" SHOPSEVCONFIG_SHOPID="F-001" SHOPSEVCONFIG_ORGPORT=5010 node app.js &
SHOPSEVCONFIG_PORT=5012 SHOPSEVCONFIG_ORGID=F SHOPSEVCONFIG_SHOPNAME="SHOP FB" SHOPSEVCONFIG_SHOPID="F-002" SHOPSEVCONFIG_ORGPORT=5010 node app.js &
SHOPSEVCONFIG_PORT=5021 SHOPSEVCONFIG_ORGID=H SHOPSEVCONFIG_SHOPNAME="SHOP HA" SHOPSEVCONFIG_SHOPID="H-001" SHOPSEVCONFIG_ORGPORT=5020 node app.js &
SHOPSEVCONFIG_PORT=5022 SHOPSEVCONFIG_ORGID=H SHOPSEVCONFIG_SHOPNAME="SHOP HB" SHOPSEVCONFIG_SHOPID="H-002" SHOPSEVCONFIG_ORGPORT=5020 node app.js &




